# Example Site settings


header_pages:
  - index.md
  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

max_width: 1024px
homepage_title: "Álvaro Martínez Majado"
append_title: "| Web d'Álvaro Martínez Majado"

plugins:
  - jekyll-seo-tag
